FROM debian:latest

RUN apt-get update && apt-get install -y curl

RUN cd /bin && \
    curl -s https://raw.githubusercontent.com/bash-unit/bash_unit/master/install.sh | bash

ENTRYPOINT ["bash", "-l"]