#!/usr/bin/env bash
DEV_ENV_DIR="$(dirname "${BASH_SOURCE[0]}")"
source "$DEV_ENV_DIR"/runner

publish_container() {
    local -r container="$1"
    local -r image="mmaarouf/$container:latest"

    echo "Building container $container"
    docker_compose build "$container"

    read -rp "Push image $image? [y/n]" ANSWER
    case $ANSWER in
        [Yy]* ) docker push "$image";;
        [Nn]* ) echo "Image not pushed.";;
    esac
}

publish_container "$DEV_CONTAINER"
publish_container "nvim-brew-env"
publish_container "nvim-apt-env"