#!/usr/bin/env bash
DEV_ENV_DIR="$(dirname "${BASH_SOURCE[0]}")"
source "$DEV_ENV_DIR"/runner

echo "Building dev env image"
docker_compose build "$DEV_CONTAINER"

echo "Buildling brew env image"
docker_compose build "nvim-brew-env"

echo "Buildling apt env image"
docker_compose build "nvim-apt-env"